apiVersion: ignite.weave.works/v1alpha2
kind: VM
metadata:
  created: "2019-08-27T15:12:56Z"
  name: git-vm
  uid: 599615df99804ae8
spec:
  cpus: 1
  diskSize: 3GB
  image:
    oci: weaveworks/ignite-ubuntu:latest
  kernel:
    cmdLine: console=ttyS0 reboot=k panic=1 pci=off ip=dhcp
    oci: weaveworks/ignite-kernel:4.19.47
  memory: 2GB
  network: {}
  ssh: true
  storage: {}
status:
  image:
    id: null
    size: 0B
  kernel:
    id: null
    size: 0B
  running: true
