apiVersion: ignite.weave.works/v1alpha2
kind: VM
metadata:
  created: "2019-08-28T15:51:59Z"
  name: new-vm
  uid: 599615df99804ae8
spec:
  cpus: 1
  diskSize: 4GB
  image:
    oci: weaveworks/ignite-ubuntu:latest
  kernel:
    cmdLine: console=ttyS0 reboot=k panic=1 pci=off ip=dhcp
    oci: weaveworks/ignite-kernel:4.19.47
  memory: 800MB
  network: {}
  ssh: true
  storage: {}
status:
  image:
    id: oci://docker.io/weaveworks/ignite-ubuntu@sha256:3285f65b2651c68b5316e7a1fbabd30b5ae47914ac5791ac4bb9d59d029b924b
    size: 206369256B
  kernel:
    id: oci://docker.io/weaveworks/ignite-kernel@sha256:bfac196a3e66d798bde3e75fc93183bb19625b09b58f30f02afb69da22f52d05
    size: 51464393B
  running: true
